model_id: "Qwen/Qwen2.5-72B-Instruct"
path_load_model: null
summary_data_path: "./data"
train_save_dir: "./train/1"
learning_rate: 2e-5
per_device_train_batch_size: 2
per_device_eval_batch_size: 2
eval_steps: 15
num_train_epochs: 25
logging_steps: 15
weight_decay: 0.01
eval_strategy: "epoch"
save_strategy: "epoch"
load_best_model_at_end: true
save_total_limit: 2
early_stopping_patience: 3
